[package]
name = "ray_tracer"
version = "0.1.0"
authors = ["Matt Stavola <mstavola9@gmail.com>"]
edition = "2018"

[dependencies]
itertools = "0.8"

[dependencies.rand]
version = "0.7.0"
features = ["small_rng"]

[profile.release]
debug = true