[output]
type = "ppm"

[renderer]
screen_width = 1280
screen_height = 720
antialias_iterations = 100
render_parallel = true
use_bounding_volume = true

[world]
max_objects = 10
is_dynamic = true

[camera]
aperture = 0.0
fov = 20.0
look_from = { x = 12.0, y = 2.0, z = 3.0 }
look_at = { x = 0.0, y = 0.0, z = 0.0 }